### ISSUE TITLE
Podcast todo

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/everything#15]
- [ ] Publish on itunes

- [ ] Publish on Stitcher

- [ ] Publish on Google Play Music

**Comment by yelluw** [comment]
- [ ] Talk to Ben Halper of dev.to to feature the podcast on their page ( > 100k users)

**Comment by yelluw** [comment]
We are officially on the Overcast FM podcast app for iOS. :)

**Comment by yelluw** [comment]
Im having an issue with SoundCloud. It won't let us have more than 2-3 episodes published due to bandwith. I'm considering putting them up on Google drive and publishing the RSS feed on the main website. What do you all think?
